### ISSUE TITLE
Šumniki se ne izpišejo pravilno

### ISSUE THREAD

**Issue by mihajan** [mihajan/Studentski-dating-app#1]
Ko admin doda novo vprašanje in besedilo vsebuje šumnike se le te ne izpišejo pravilno. Očitno je isto tudi pri dodajanju novih oseb z šumniki. Težava mora biti nekje v med htmlji in services, saj funkcije iz repo šumnike obravnavajo pravilno

**Comment by majbc1999** [comment]
Živjo,

problem je v "branju" form iz htmljev. Nisem našel bolj elegantne rešitve, kakor da vedno ko kličeš `request.forms` narediš naslednji trik:

```python
@post('/dodaj_vprasanje')
@cookie_required
def dodaj_vprasanje():
    vprasanje_text = request.forms.get('vprasanje').encode('iso-8859-1').decode('utf-8')
    service.dodaj_vprasanje(vprasanje_text)
    redirect('/urejanje') 
```

Meni s pomočjo tega sedaj uspešno bere in zapisuje v bazo vse šumnike.
