### ISSUE TITLE
Binder ne dela - Could not find path: proxy/8080

### ISSUE THREAD

**Issue by jankovicnina** [mihajan/Studentski-dating-app#3]
Please zakaj to ne dela, naredila sem vse, kakor je na spletni:( 
Na koncu ti sploh ne odpre lepo Binder ampak hub.binder karkoli je to in samo reče Could not find path: proxy/8080.

**Comment by majbc1999** [comment]
Živjo, 

ko te vrže na hub.binder, lahko tam odpreš terminal in napišeš `python app.py`. 
![image](https://github.com/mihajan/Studentski-dating-app/assets/49946994/ab0f3b31-e8e1-4298-9f05-8951cb418ead)

Potem se ti lepo izpiše, kje so težave. To je super orodje za testiranje.

Zaenkrat zgleda, da je problem, ko uvoziš `from Data.models ...` namesto `from Data.Models` (velika začetnica).
![image](https://github.com/mihajan/Studentski-dating-app/assets/49946994/bc17fdf8-2f2d-4180-b1dc-c2443a2cb23d).

**Comment by jankovicnina** [comment]
Okej hvala, to sem zdej popravla. Ampak še vedno ne builda, ven mi pa terminal meče periodično isti error, da je adress že v uporabi. Sva dodala neko funkcijo, ki naj bi našla free port ampak ne pomaga ...

**Comment by jankovicnina** [comment]
> Živjo,
> 
> ko te vrže na hub.binder, lahko tam odpreš terminal in napišeš `python app.py`. ![image](https://private-user-images.githubusercontent.com/49946994/339276278-ab0f3b31-e8e1-4298-9f05-8951cb418ead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMTQzMjQsIm5iZiI6MTcxODMxNDAyNCwicGF0aCI6Ii80OTk0Njk5NC8zMzkyNzYyNzgtYWIwZjNiMzEtZThlMS00Mjk4LTlmMDUtODk1MWNiNDE4ZWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDIxMjcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNjVhMWI1ODIwMDU2Y2U0Y2MyYTM5MGUwNzMxOTUxYzJjZGY5ZDZjY2Q2YzU5NDBlMDNiNjkwMDU4NzhhYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-qhr6j0ThHFusk3DSq2tY79QSTeqDKcUaI_H5MW9x10)
> 
> Potem se ti lepo izpiše, kje so težave. To je super orodje za testiranje.
> 
> Zaenkrat zgleda, da je problem, ko uvoziš `from Data.models ...` namesto `from Data.Models` (velika začetnica). ![image](https://private-user-images.githubusercontent.com/49946994/339276722-bc17fdf8-2f2d-4180-b1dc-c2443a2cb23d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMTQzMjQsIm5iZiI6MTcxODMxNDAyNCwicGF0aCI6Ii80OTk0Njk5NC8zMzkyNzY3MjItYmMxN2ZkZjgtMmYyZC00MTgwLWIxZGMtYzI0NDNhMmNiMjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDIxMjcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNjJjMTczYjA1NmVkNjkyOTE1YzU3YTRmNTJlOTI5MWRiMmEyOWE0MTliMDkwN2U3OGM4ZjU5MmUzMTJhMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DIidJf_XdYt_8djMQU32B11Ktd3TqGb7oPM9-X4vmxw).

ne vem točno kako tole deluje, tako da zdej replyam na tvoj odgovor za vsak slučaj (ker ne vem, če dobiš obvestilo za post na issue):)

**Comment by majbc1999** [comment]
Živjo,

ni treba replyati, dobim vseeno obvestilo na mail ob vsakem komentarju na issue :D.

Torej, opazil sem nekaj težav v kodi in sicer je glavna ta, da ne konsistentno uporabljata funkcije `url` za preusmeritve. V Binderju je to nujno potrebno, sicer nič ne dela.

Funkcijo `url` je treba uporabiti tako v Pythonu (povsod kjer je `redirect`) in tudi povsod v html-jih. Na primer:

```html
<div class="row">
                <form class="col s12" method="POST" action="/prijava">
                    % if napaka:
                            <div class="error-message">
                                {{napaka}}
                            </div>
```

To ne bo delovalo, potrebna je funkcija url:
```html
```html
<div class="row">
                <form class="col s12" method="POST" action="{{url('prijava')}}">
                    % if napaka:
                            <div class="error-message">
                                {{napaka}}
                            </div>
```

Pazita, da funkciji `url` vedno podata ime funkcije iz `app.py` in ne route. Če Binder po tem popravku še vedno ne bo deloval, javita :)

**Comment by jankovicnina** [comment]
Zdravo, zdaj sva "popravila" na dva različna načina (sta vsak v svojem branchu). Težava pa je, da se v nobenem primeru binder ne naloži, saj že takoj vrže Internal server error. Zdaj počasi postajava res jezna na ta binder:)))))))))))))))))))))))))

**Comment by majbc1999** [comment]
Živjo,

ne vem točno kje je problem v `Internal server errorju`. Ali se je to začelo dogajati odkar imata 2 brancha? Sem namreč forkal repozitorij in samo spremenil binder link na forked repozitorij in mi vsaj zbuilda:
![image](https://github.com/mihajan/Studentski-dating-app/assets/49946994/60696aea-05fa-4f78-99b0-3018554cafc2)

Kaj točno je razlika med obema branchoma?

**Comment by jankovicnina** [comment]
Težava se je pojavila že prej, zato sem na podoben način preuredila url klicanje (in ga dala v nov branch da stestirava kjer je težava). Sem mislila, da je problem v sami datoteki in zato binderja ne odpre. Potem je pa tudi na novem branchu bil enak error. Težave imava tudi z drugimi projekti (ko npr probava runnat binder na Gašperjevemu ali Vidalijevemu projektu nama vrne enak error).

**Comment by mihajan** [comment]
![image](https://github.com/mihajan/Studentski-dating-app/assets/64685191/be8109ed-709e-4a26-9c12-30bf490d2fc2)
Živjo, midva sva trenutno res brez idej kaj je narobe. Od včeraj mi ne uspe odpreti skoraj nobenega binderja. Prilagam sliko kaj mi napiše ob poskusu odpiranja Gašperjevega projekta. Identični mi napiše tudi za najinega in npr. Vidalijevega. 
Z googlenjem si tudi nisva uspela preveč pomagati, vse kar sva našla v zvezi s tem errorjem je, da jim je manjkal requirements file, ki pa ga vsi te projekti imajo. Poskusila sva tudi narediti nov github repozitorij in vso najino kodo prekopirati tja notri in se je ponovila ista napaka. Recimo, če pa poskusim v mybinder dat link do kakšnega drugega mojega repozitorija, ki sploh ni bil namenjen za binder pa vsaj začne nekaj nalagati.

Sicer pa sva dva brancha naredila predvsem zato, ker sva oba hkrati nekako poskusila to rešit. Bistvenih razlik med njima ni, razlikujeta se edino v tem katere funkcije kličeva v htmljih. Eden kliče pogosto post metode iz appa, drugi pa ne.
Če imaš še kakšno idejo kaj bi lahko spremenila ali kako nekako debuggat to se seveda priporočava.:)

**Comment by majbc1999** [comment]
Živjo,
nimam pojma kaj bi lahko bil vajin problem. Imaš ti kakšno idejo, @gasperxy?

Sicer pa, ali je projekt (brez Binderja) pripravljen na oddajo (da v tem primeru pregledam)?

**Comment by jankovicnina** [comment]
Ne vem, kako je to možno, ampak danes nama binder dela. Sva posodobila in popravila vse, kar je bilo še za popraviti. Projekt je zaključen:)

**Comment by majbc1999** [comment]
Evo, sem pregledal projekt in super deluje, pohvale tudi za zgodbico v README. Če se še nista, se lahko z @jaanos zmenita za zagovor :)
